### ISSUE TITLE
Make a good docs

### ISSUE THREAD

**Issue by riolly** [riolly/create-t3-extended#1]
Self describes.

The task to be done:

- [x] More explanation about why add that stack
- [x] More links to related resource
- [x] Use markdown format correctly
- [x] Add path aliases to the table of content
- [x] Globals style on scss format
- [x] Implement google OAuth to the template
- [x] Note on using other that npm

**Comment by makyfj** [comment]
@riolly I like this repo and now I'm using for every new t3 project I create, I would like to add yarn as well because I personally use yarn more than npm.

**Comment by riolly** [comment]
Thank you for your support @makyfj. I want to clean up the docs a little bit first. You can check my review also.
